### ISSUE TITLE
Add ggFishPlots to Fisheries-Related R Packages?

### ISSUE THREAD

**Issue by MikkoVihtakari** [fishR-Core-Team/fishR#4]
Thanks for a great website. I was wondering whether ggFishPlots (https://deepwaterimr.github.io/ggFishPlots/) could be added somewhere here: https://github.com/fishR-Core-Team/fishR/blob/f25a273daceedefaaf1f0f9345eac9dbc3269e87/pages/packages.qmd#L43

This is a similar package to AquaticLifeHistory with a ggplot2 twist. It contains the life history functions I have needed in my work. It should be on CRAN soon.

**Comment by droglenc** [comment]
Done ... see [here](https://fishr-core-team.github.io/fishR/pages/packages.html#more-focused).

Looks interesting. Thanks for sharing.

**Comment by MikkoVihtakari** [comment]
Thanks! Perhaps add s after ggFishPlot (i.e. ggFishPlot**s**)

**Comment by droglenc** [comment]
Sorry. Fixed it. Thanks.
