### ISSUE TITLE
Possible error in model formula

### ISSUE THREAD

**Issue by abner-hb** [fishR-Core-Team/fishR#9]
In [the formula](https://fishr-core-team.github.io/fishR/blog/posts/2024-2-5_LVB_brms/) $TL_i=L_\infty * (1-e^{(-\kappa * (t_i-t_0))} + \epsilon_i)$, the error term $\epsilon_i$ should not be inside the parenthesis, but outside. As currently written, the formula implies that $\epsilon_i$ is multiplied by $L_\infty$. To reflect this, $\epsilon_i$ would need to appear in `brmsformula` as a non-linear parameter, but the current code does not do this (and I don't think it should).

**Comment by jcdoll79** [comment]
Hi, Thank you for pointing out the typo! This has been fixed in the Bayesian LVB I and Bayesian LVB II posts. The changes should show up on the site soon.
